name: Maven Build and Docker Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env_slug:
        description: 'Environment Slug'
        required: true
        default: 'dev'
      namespace:
        description: 'Kubernetes Namespace'
        required: true
        default: 'dev'
      destroy:
        description: 'Destroy all resources'
        required: true
        default: 'false'
        type: boolean
      is_canary:
        description: 'Canary Deployment'
        required: true
        default: 'false'
        type: boolean
      is_canary_destroy:
        description: 'Canary Destroy'
        required: true
        default: 'false'
        type: boolean

jobs:
  App_Tests:
    runs-on: ubuntu-latest
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    # Perform Maven build
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Maven Build
      run: mvn install

    - name: Unit Test
      run: mvn test

  deploy-develop:
    needs: App_Tests
    if: github.ref == 'refs/heads/main' && github.event.inputs.destroy == 'false' && github.event.inputs.is_canary_destroy == 'false' && github.event.inputs.is_canary == 'false'
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build(Using Action)
      uses: marocz/kdh-github-action@v0.0.1.1
      with:
        CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
        KUBE_URL: ${{ secrets.KUBE_URL }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
        KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
        CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
        CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
        CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        CI_REGISTRY: ghcr.io
        CLUSTER: ${{ secrets.CLUSTER }}
        COMMAND: "command build"

    # - name: Deploy
    #   run: |
    #     command deploy

  deploy-staging:
    needs: App_Tests
    if: github.ref == 'refs/heads/staging' && github.event.inputs.destroy == 'false' && github.event.inputs.is_canary_destroy == 'false' && github.event.inputs.is_canary == 'false'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build
      run: |
        command build

    - name: Deploy
      run: |
        command deploy

  deploy-production:
    needs: App_Tests
    if: github.ref == 'refs/heads/production' && github.event.inputs.destroy == 'false'  && github.event.inputs.is_canary == 'false' && github.event.inputs.is_canary_destroy == 'false'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build
      run: |
        command build

    - name: Deploy
      run: |
        command deploy

  canary:
    needs: App_Tests
    if: github.event.inputs.is_canary == 'true'  && github.event.inputs.is_canary_destroy == 'false'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}
    

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build
      run: |
        command build

    - name: Deploy
      run: |
        command deploy-flagger



  destroy-develop:
    needs: App_Tests
    if: github.ref == 'refs/heads/main' && github.event.inputs.destroy == 'true'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Destroy
      run: |
        command destroy

  destroy-staging:
    needs: App_Tests
    if: github.ref == 'refs/heads/staging' && github.event.inputs.destroy == 'true'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Destroy
      run: |
        command destroy

  destroy-production:
    needs: App_Tests
    if: github.ref == 'refs/heads/production' && github.event.inputs.destroy == 'true'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Destroy
      run: |
        command destroy

  destroy-canary:
    needs: App_Tests
    if: github.ref == 'refs/heads/production'  && github.event.inputs.is_canary_destroy == 'true'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ghcr.io/marocz/spring-k8s-deploy-helper-examples
      KUBE_URL: ${{ secrets.KUBE_URL }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CA_PEM: ${{ secrets.KUBE_CA_PEM }}
      KUBE_NAMESPACE: '${{ github.event.inputs.namespace }}'
      CI_ENVIRONMENT_SLUG: '${{ github.event.inputs.env_slug }}'
      CI_ENVIRONMENT_URL: 'http://spiringboot.marocz.com'
      CI_DEPLOY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      CI_REGISTRY: ghcr.io
      CLUSTER: ${{ secrets.CLUSTER }}

    container:
      image: marocz/k8s-deploy-helper-github:1.1.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Destroy
      run: |
        command destroy
